### ISSUE TITLE
Full functionality not available on M1

### ISSUE THREAD

**Issue by realityacid** [jirutka/zsh-shift-select#2]
Hello,

I installed this as an oh-my-zsh plugin. However, only the shift + arrow function works, the highlighting of whole words and all of the other features don't. This is still better than nothing, but it'd be great if I could get the full word/line highlighting available. Your input is appreciated. Thanks :)

System:
Macbook M1

**Comment by jirutka** [comment]
Hi, this has nothing to do with CPU architecture, but with terminal settings. See [Known Issues](https://github.com/jirutka/zsh-shift-select#known-issues) in the readme. What terminal emulator do you use?
