### ISSUE TITLE
only works in xterm

### ISSUE THREAD

**Issue by Alistair1231** [jirutka/zsh-shift-select#3]
Hi. I am playing around with this for a while now. 
I am now using prezto together with zgenom to load my plugins.
My issue is, that I can only get your plugin to work on xterm. I normally use either Konsole or Yakuake. 
My suspicion is that the keyboard codes are different, I'm not sure though.
Any input on how to make it work?

**Comment by jirutka** [comment]
Hi, did you read [Known Issues](https://github.com/jirutka/zsh-shift-select#known-issues) in the readme?
