### ISSUE TITLE
copy selected text?

### ISSUE THREAD

**Issue by birgersp** [jirutka/zsh-shift-select#4]
Hey,

Is there a way to copy the highlighted text?

**Comment by NicolasArteaga** [comment]
I tried to program it, but it looks like a pain. You can see the explanation [here](https://unix.stackexchange.com/questions/620958/what-are-zsh-commands-for-cut-copy-paste) 
@jirutka Do you think you could program it? Or what would you suggest?
Thanks

**Comment by jirutka** [comment]
Hi,
what exactly do you mean by “copy”? If you mean copying within Zsh, to the “kill buffer”, it’s mentioned at the bottom of the [Key Bindings](https://github.com/jirutka/zsh-shift-select#key-bindings) section:

> You can use default Alt+W or Ctrl+W key bindings to copy (copy-region-as-kill) or cut (backward-kill-word) selected text to the “kill buffer”, and Ctrl+Y to paste (yank) the contents of the “kill buffer”.

If you mean copying to the system clipboard, that’s a bit more complicated and it depends on your environment. Take a look into [alpine-zsh-config: 70-clipboard.zsh](https://github.com/jirutka/alpine-zsh-config/blob/master/zshrc.d/70-clipboard.zsh) for inspiration (wl-clipboard / xclip is used for a local clipboard, [tty-copy](https://github.com/jirutka/tty-copy) for remote (when you’re connected via SSH)).

**Comment by birgersp** [comment]
I meant copying to the system clipboard. Would it be possible to use xclip when available (which I guess would include most users)?

**Comment by jirutka** [comment]
> Take a look into [alpine-zsh-config: 70-clipboard.zsh](https://github.com/jirutka/alpine-zsh-config/blob/master/zshrc.d/70-clipboard.zsh) for inspiration (wl-clipboard / xclip is used for a local clipboard, [tty-copy](https://github.com/jirutka/tty-copy) for remote (when you’re connected via SSH)).
