### ISSUE TITLE
Custom key bindings?

### ISSUE THREAD

**Issue by eggbean** [jirutka/zsh-shift-select#6]
> If you want to add custom key bindings to manipulate with active selection, define them in the shift-select keymap (bindkey -M shift-select …​).

Could you please explain this a bit more? Can I add vim-like bindings that only work when text is selected by this plugin?

I would like to add `x` to put text into the kill buffer, like `ctrl-w` does. This would be more convenient me after navigating back using vim-mode temporarily (ctrl-x,ctrl-v). I can't remember how I enabled this key binding for temporary vim-mode.

**Comment by jirutka** [comment]
> Can I add vim-like bindings that only work when text is selected by this plugin?

Yes, the keymap is named `shift-select`, you can see is [here](https://github.com/jirutka/zsh-shift-select/blob/da460999b7d31aef0f0a82a3e749d70edf6f2ef9/zsh-shift-select.plugin.zsh#L97).
