### ISSUE TITLE
Doesn't work on a fresh zshrc

### ISSUE THREAD

**Issue by Lassebq** [jirutka/zsh-shift-select#7]
Using oh my zsh's zshrc seems to work however.
Something else gets sourced in oh my zsh which makes this plugin work

**Comment by Lassebq** [comment]
Seems to be lib/key-bindings.zsh which fixes it. You could add that to the plugin so that it works outside of oh my zsh

**Comment by jirutka** [comment]
> Seems to be lib/key-bindings.zsh which fixes it.

What is this file, how does it fix it?

This plugin is only a single .zsh file, it’s up to you how/where you source it. It doesn’t depend on Oh My Zsh in any way, I don’t even use it.

**Comment by Lassebq** [comment]
Nevermind, looks like it's working again even without this omz plugin. I have no idea what caused it, but when I was remaking my zshrc this plugin refused to work.
